#!/usr/bin/perl -w
use strict;

my ($imagepath, $setting);

my $scriptoutput = q(
echo '#!/bin/tcsh

#SBATCH --time=50:00:00   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=3072M   # memory per CPU
#SBATCH -J "rerun"   # job name
#SBATCH --mail-user=csfinuf777@gmail.com  # email address
#SBATCH --mail-type=FAIL

setenv FREESURFER_HOME /fslhome/username/apps/freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.csh
setenv SUBJECTS_DIR /fslhome/csfinuf/Users/csfinuf/Desktop/freesurfer/UCSD

recon-all -s %1$s -autorecon2-wm -autorecon3

exit 0 

' | sbatch 

);




while (my $inputline = <STDIN>) {
	chomp($inputline);

	my @inputfields = split /,/, $inputline;

	if(scalar(@inputfields) != 1) { #wrong number of fields; something must be wrong
		print "Error reading record: wrong number of fields in input line \"$inputline\": ", scalar(@inputfields), " fields\n";
	} else  {
		system(sprintf($scriptoutput, @inputfields) );
	}
	print "------------------------------------========================================------------------------------------\n";
	
}
